OpenCAPI AxiTop changes
johanpel/fletcher pull request #219
Opened 2020-01-31 12:56 UTC by joosthooz

I'm having some trouble getting a fletcher design into OpenCAPI, this branch contains some changes to fix this.

2020-03-13 15:32 UTC, johanpel requested changes
Apart from the modifications to the Makefile, it looks good to me.

2020-03-13 15:32 UTC, johanpel commented on examples/stringwrite/hardware/Makefile
> +	fletchgen -i stringwrite.as -t memory.srec -l vhdl dot --sim --axi --regs c:32:strlen_min c:32:strlen_mask
This should not be part of the Makefile as it is meant for simulation only.

2020-03-13 15:32 UTC, johanpel commented on examples/sum/hardware/Makefile
> +	fletchgen -n Sum -r recordbatch.rb -s memory.srec -l vhdl --sim --axi
This should not be part of the Makefile as it is meant for simulation only.

2020-03-17 16:54 UTC, joosthooz commented
The AXI top generation has been removed from the Makefiles, but do have a look at
1) the sensitivity list
2) the assertions
Both are needed because of the OpenCAPI simulation environment. I already discussed point 2 with Jeroen btw.

2020-03-20 12:41 UTC, johanpel requested changes

2020-03-20 12:41 UTC, johanpel commented on hardware/interconnect/BusReadBuffer.vhd
> +            severity WARNING;
This should remain an error or else deadlocks occurring in simulation might slip the attention of the user, and result in massive penalties in development time.

2020-03-20 12:41 UTC, johanpel commented on hardware/interconnect/BusReadBuffer.vhd
> +            severity WARNING;
This should remain an error or else deadlocks occurring in simulation might slip the attention of the user, and result in massive penalties in development time.

2020-04-07 08:49 UTC, merged